name: Deploy app

on:
  workflow_run:
    workflows: ["Build image"]
    types:
      - completed

jobs:
  deploy-beta-app:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Stack Deploy
      uses: cssnr/stack-deploy-action@v1
      with:
        name: activities-beta
        file: infra/beta/docker-stack.yaml
        host: beta.activities.training
        user: deploy
        ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}