name: Deploy app

on:
  workflow_run:
    workflows: ['Build image']
    types:
      - completed

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: tchoutchou
          file: docker-stack.yaml
          host: train.trackforge.fr
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
